//! Patch notes shown under "WHAT'S NEW" on the main-menu screen
//! ([`crate::lobby_ui::build_browser`]) — the only place players see what
//! changed between releases, since the client updates itself silently
//! (`updater.rs`) with no other notification.
//!
//! AI agents and contributors: whenever you finish a feature or bug fix that
//! ships to players, add one line to `ENTRIES` under the current in-progress
//! version (newest version first, newest line within a version first). This
//! doesn't happen automatically — if you don't add the line here, players
//! never see it.

/// `(version, notes)`, newest version first. `version` is the tag this will
/// ship under — keep it in sync with the workspace `Cargo.toml` `version`
/// (bump both together when starting the next round of changes).
pub const ENTRIES: &[(&str, &[&str])] = &[(
    "0.4.6",
    &[
        "Zombies: round number on screen, with a sound and animation each new round.",
        "Zombies: turn on the power on Break Point Night to light up the map.",
        "Zombies: real, solid perk machines for every perk.",
        "Liquid Courage: strong double vision right after drinking.",
        "Zombies: perk machines play their jingle when anyone buys one.",
        "New melee key (E): quick knife stab straight from the sniper.",
        "New Call of Duty style menus, lobby and loadout screens.",
        "New map: BREAK POINT NIGHT — full night, with gun flashlights.",
        "Red X on kills; hit markers now burst outward.",
        "Zombies: new, bigger perk icons.",
        "Shroom Tea: enemies only glow when hidden behind cover.",
        "Zombies: Shroom Tea and Liquid Courage hit hard for a few seconds after drinking.",
        "Zombies: new Liquid Courage perk — take less damage.",
        "Party leader can now pause the game from the Esc menu.",
        "Other players' rechamber is much quieter; no more aim sounds.",
        "Kill sound is a little quieter.",
        "Zombies: kill sound no longer plays twice.",
        "Zombies: new perk machine card with cost, points and ingredients.",
        "Zombies: perk icons line up in the order you bought them.",
        "Zombies: new Nitro Brew perk — move, aim, reload and swap faster.",
        "Zombies: you now drink Shroom Tea when you buy it.",
        "Zombies: buying Shroom Tea now plays a drink sound.",
        "Zombies: enemies-left counter on the left of the screen.",
        "Shroom Tea adds a slight aim assist while aiming down sight.",
        "Shroom Tea lets you see enemies through walls.",
        "Zombies: party points, health and names in the bottom left.",
        "Zombies: owned perks show as icons at the bottom.",
        "Zombies: buy the Shroom Tea perk on Break Point.",
        "New mode: ZOMBIES. Survive rounds of bots with your party.",
        "Throwing knives now leave a faint trail, in kill cams too.",
        "You can now jump just after running off a ledge.",
        "You can no longer run through other players and bots.",
        "Bots now have dark blue armour so you can tell them apart.",
        "Ping bots in Freestyle with middle mouse; your whole lobby sees it.",
        "Added name tags over players (blue in Freestyle, red in Free For All).",
        "Freestyle bots now use the soldier model and walk around the map.",
        "Added a ping (ms) readout beside the FPS counter.",
        "Sniper ammo is now limited in Free For All: 6 mags per life.",
        "New Call of Duty style ammo HUD, with throwing knives shown.",
        "Throwing knives are now limited: 2 per life in Free For All.",
        "Removed the Ascension map.",
        "Other players (and bots) now show a bright sniper glint off their scope while they're aiming down sight — just like Call of Duty, it can give away a camping sniper's position.",
        "Fixed the red tint and blood splatter overlay covering up your HUD (health, ammo, hit markers, etc) when you take damage or die. It now stays behind all on-screen text and UI.",
        "Fixed the red tint and blood splatter (and heartbeat) staying on screen after you respawn. Respawning now fully resets you: health, the hurt effects, camera shake, aiming, sprint / slide / mantle state, and any half-finished trick or shot. The server brings you back to life the moment you respawn, too, so skipping your kill cam no longer leaves you unable to hit anyone until a timer runs out.",
        "Fixed being able to move, aim, shoot and throw knives after being killed while waiting for the kill cam to start. Once you're dead you can't do anything except open the menu with Escape and use it.",
        "Kill cams now show everyone else as they really were during the replay: bots and other players walk, aim, crouch, jump and fall over when and where they actually did, instead of standing frozen where they were at the moment of the kill.",
        "The moment a Free For All match ends (kill limit reached or time up) the game freezes for 2 seconds: no movement, aiming or shooting, and nothing that happens counts. The screen flashes white, then VICTORY (green) or DEFEAT (red) slams in. After that the end-of-match replay plays — and it can no longer be skipped — then the final results screen.",
        "Free For All matches now end with a replay for everyone, whoever won. The party leader picks which in the lobby (everyone can see the choice): BEST PLAY — the most kills one player got within 8 seconds, replayed from a few seconds before the first kill to just after the last (two quick kills make a short replay; five kills in 8 seconds play the whole 8) — or FINAL KILL — just the last kill of the match. Both play with the same ramped slow-mo as Freestyle's best play.",
        "New map: BREAK POINT, a walled compound of low buildings, blocks and raised walkways, on a bright, cloudless mid-day with crystal-clear visibility all the way to the horizon. Pick it from the map buttons in the lobby.",
        "The Ascension map is now the same scale as the basic map (35% smaller all round), so it feels the right size to move around in. Bots on it also get around ledges and ramp turns better.",
        "Kill cams of a bot killing you look much more natural: the bot now scopes in gradually instead of snapping to full aim, and you see its rifle recoil, camera shake and bolt-cycle after each shot.",
        "Shipment (and Shipment Day) now has 11 fixed spawn points. When a match starts, and every time anyone respawns, players and bots appear at a random one of them, already facing the direction set for it and looking level.",
        "Bots now find their way around: they plan a route through the map (around walls and containers, up and down ramps) instead of walking straight at you.",
        "Free For All lobbies can now have bots! The party leader picks a number (up to 20) and a difficulty (Recruit, Regular, Hardened or Veteran) and presses ADD BOTS — add as many batches as you like, up to 20 bots in total. Bots show up in the party with their own names, walk around the map and shoot at everyone: you and each other. If one kills you, you get a kill cam of it. (They're basic for now: no pathfinding, so they can get stuck behind walls.)",
        "New map: ASCENSION, a multi-level blockout you climb by ramps, set on a snowy mountain hillside under a slightly overcast sky. Pick it from the map buttons in the lobby.",
        "Health is now handled entirely by the server: fall damage and shot damage take from the same health bar, and the red tint, blood splatter and heartbeat now also show when you're shot without being killed. Falls hurt in Freestyle too.",
        "Sniper damage now depends on distance too. Up close every hit kills, even a leg shot; further out a leg shot stops killing (past about 70 m), then a torso shot (past about 175 m), and at extreme range (past about 250 m) even a headshot leaves the target alive.",
        "Sniper shots are no longer always one-shot kills: a hit to the legs or lower body only does 60% damage, so the target survives (bots and players both have health now). When you damage but don't kill someone you get a hit marker and sound. In Free For All, damaged players heal back after 3 seconds.",
        "Fall damage: landing from a big drop now hurts in proportion to how far you fell (nothing under 16 m, dead at 30 m). When you're hurt the screen tints red with a blood splatter and you hear a heartbeat, both stronger the lower your health. Health holds for 3 seconds, then builds back up.",
        "The throwing arms (and the knife in their hand) now sway when you turn and breathe while you stand still, just like the sniper, and the regular knife now breathes too.",
        "Added a sound for switching to the sniper (only you hear it).",
        "Added knife sounds: an equip sound when you switch to the knife (only you hear it), a stab sound when you stab a bot or player (everyone hears it from the victim), and a swing sound when you attack and miss (everyone hears it from you). Volumes are in the debug panel. Throwing knife impact sounds are also quieter now.",
        "A thrown knife now makes an impact sound (one of several, picked at random) from the spot where it hits a wall, the ground or a crate. Everyone in the lobby hears it, and each clip has its own volume slider in the debug panel.",
        "Added throwing knife sounds: a throw sound when you let go (other players hear it from where you are), a whoosh that follows the knife through the air for everyone, and a hit sound from the spot where a thrown knife kills a bot or player. Volumes are in the debug panel.",
        "Shots now leave bullet holes on the surfaces they hit, and everyone in the lobby sees them. They disappear after a minute.",
        "Fixed: the throwing knife crosshair now shows in kill cams (and stays up while the throwing arms are on screen) instead of the plain centre dot.",
        "Fixed: kill cams now show the throwing arms and the knife being thrown (and flying, bouncing and landing the kill), instead of leaving them out.",
        "Shots no longer go through walls, crates or containers: a bullet (and its tracer) stops at the first surface it hits, so you can't hit anything behind cover.",
        "You can now actually throw the throwing knife! Hold V, aim and let go. It flies in an arc, bounces off walls and the ground, losing speed each time, then stops and disappears. Everyone in the lobby sees it. In Freestyle it kills bots (40 points); in Free For All it kills other players.",
        "The throwing arms now hold a throwing knife while you hold V. It disappears the moment the throw animation starts.",
        "Holding the throwing knife key (V) now quickly puts your weapon away, then slides a pair of throwing arms up from below. Let go and they play a throw animation and slide back down, and only then does your weapon come back. Press the swap-weapon key while holding to cancel without throwing. There is no knife to throw yet.",
        "Removed PRACTICE mode. Every game now runs through the server: create a lobby (or join one) and start it to play. Freestyle still gives you bots to shoot at.",
    ],
)];
