//! Patch notes shown under "WHAT'S NEW" on the main-menu screen
//! ([`crate::lobby_ui::build_browser`]) — the only place players see what
//! changed between releases, since the client updates itself silently
//! (`updater.rs`) with no other notification.
//!
//! AI agents and contributors: whenever you finish a feature or bug fix that
//! ships to players, add one line to `ENTRIES` under the current in-progress
//! version (newest version first, newest line within a version first). This
//! doesn't happen automatically — if you don't add the line here, players
//! never see it.

/// `(version, notes)`, newest version first. The main menu's "WHAT'S NEW"
/// panel shows only the first (current) version; every older one lives on
/// the PAST UPDATES screen (`menu::Screen::Changelog`). `version` is the tag
/// this will ship under — keep it in sync with the workspace `Cargo.toml`
/// `version` (bump both together when starting the next round of changes).
pub const ENTRIES: &[(&str, &[&str])] = &[(
    "0.4.7",
    &[
        "Zombies: fixed shots to a boss's upper body and head not counting.",
        "Zombies: zombies, hellhounds and bosses bleed when hit — more on the kill.",
        "Zombies: fixed zombies flashing in the middle of the map on spawn.",
        "Zombies: smaller perk icons.",
        "Zombies: dog rounds only drop their Max Ammo.",
        "New equipment and AK-74 icons; the tactical slot is always shown.",
        "Zombies: crafting table — buy lethals and tacticals.",
        "Zombies: the monkey bomb is now a tactical (Q).",
        "Zombies: flash bangs — a new tactical (Q) that stuns zombies.",
        "Swap Weapon now defaults to 1 (Q is the tactical).",
        "Zombies: players start on each map's own spawn spots.",
        "Zombies: frag grenades — cook them, but don't hold on too long.",
        "Fixed the results screen coming back in the next game.",
        "Zombies: a short pause before the results screen.",
        "Zombies: exfil — every 10th round, call it in at the radio and escape.",
        "Zombies: new intro screen while the game loads.",
        "Zombies: a boss joins every 7th round — smashes up close, hurls fireballs from afar.",
        "Zombies: Max Ammo fills both guns, mags included — no reload needed.",
        "Fixed a doubled or huge gun when a game starts right after launching.",
        "Zombies: damage numbers show only the health the hit took.",
        "Weapon name under its icon — coloured by its Pack-a-Punch level.",
        "Fixed sometimes falling through the map as a game starts.",
        "Zombies: new Pack-a-Punch machine — it glows and vents fog once the power's on.",
        "Zombies: the Aether Shroud field upgrade (X) — vanish from zombies.",
        "Playing alone? The pause menu just has LEAVE GAME.",
        "Zombies: the Monkey Bomb — lure zombies in, then boom.",
        "No more aiming in while holding a lethal.",
        "Zombies: armor — buy up to 3 levels at the armor station.",
        "Added a compass to the top of the screen.",
        "Zombies: the Mystery Box.",
        "Zombies: the Ray Gun (debug only for now).",
        "Zombies: bled out? Spectate a teammate until the next round.",
        "Zombies: no weapon in hand while down.",
        "New end of game screen, with each player's kills, revives and downs.",
        "Zombies: new round number font.",
        "Zombies: drop and pick up weapons, which keep their ammo and Pack-a-Punch.",
        "Zombies: wall buys for the sniper and AK-74.",
        "Level editor: scale objects, player's-eye view, reference player and zombie.",
        "Added a Zombies level editor (main menu).",
        "Zombies: sounds when a teammate goes down and when a revive finishes.",
        "Zombies: going down no longer ends the game — teammates can revive you.",
        "Zombies: Quick Revive revives faster, and revives you when playing solo.",
        "Zombies: your operator says a line after buying a perk.",
        "Zombies: pick your operator (Adam or Von) in the lobby.",
        "Fixed the game assets download cutting off on fresh installs.",
    ],
), (
    "0.4.6",
    &[
        "Zombies: every 5th round is a hellhound round!",
        "Zombies: the last hellhound of a dog round drops a Max Ammo.",
        "Zombies: perk machines vent cold fog once the power is on.",
        "Zombies: no more birdsong — just the zombies ambience.",
        "Sniper, knife and throwing knife now bob as you walk and sprint, like the AK-74.",
        "Lobby: leaving now asks you to confirm.",
        "Zombies: damage numbers pop off zombies when you hit them.",
        "Zombies: kill points are white, yellow for criticals.",
        "Mouse back button now works as back in menus and lobbies.",
        "Added a loading screen on launch, so the menu no longer pops in half-drawn.",
        "Settings: new music volume slider for the main menu music.",
        "You can now see other players swing their knife.",
        "Zombies: throwing knives always kill in one hit.",
        "Zombies: the ammo crate is now solid.",
        "Zombies: molotov fire does double damage.",
        "Zombies: optional pre-game countdown (up to 2 minutes) to get set up before round 1.",
        "Zombies: classic perks are now the default.",
        "PhD Flopper: faster slides that leave a trail of purple fire.",
        "PhD Flopper: sliding into a zombie stops your slide.",
        "PhD Flopper: zombies that survive the blast are stunned.",
        "Lobby: pick Shipment or Break Point, then day or night.",
        "Zombies: Break Point by day now has Pack-a-Punch and the power switch too.",
        "Zombies (classic perks): Der Wunderfizz wakes up on round 17.",
        "Fixed see-through-walls perks lighting up zombies' own limbs.",
        "Zombies: classic Call of Duty perks! Pick PERKS: CLASSIC in the lobby.",
        "Guns now have real recoil: each shot kicks your aim up and sideways.",
        "Free For All: AK-74 damage lowered.",
        "Shot tracers now come out of the gun barrel.",
        "Free For All: AK-74! Pick it in your loadout.",
        "New Call of Duty style Loadout and Gunsmith screens.",
        "Free For All: change loadout mid-match (applies on spawn).",
        "AK-74 muzzle flash now follows the barrel when aiming.",
        "ADS sensitivity now scales with each weapon's zoom (new Monitor Distance Coefficient setting).",
        "Zombies: AK-74! Pick it in the lobby's new Loadout section.",
        "Zombies: health bars over zombies you hit.",
        "Zombies: power-up glow no longer cut off by walls or drawn over the power-up.",
        "Zombies: go prone at a perk machine for a little something.",
        "Zombies: +50 points for headshot and knife kills.",
        "Zombies: new power-up look.",
        "Zombies: Nuke freezes zombies, burns them down over 5 seconds, gives 500 points.",
        "Zombies: buying ammo fills your mag too.",
        "Zombies: Pack-a-Punching your sniper fills its mag and ammo.",
        "Zombies: sniper one-shots zombies for longer, with or without Pack-a-Punch.",
        "Zombies: one lethal at a time. Walk over your kind to grab it, swap with interact (up to 4).",
        "Zombies: molotovs burn zombies twice as hard.",
        "Zombies: Kangabrew halves fall damage.",
        "Knife reaches a little further.",
        "Zombies: zombies get tougher every round.",
        "Zombies: Pack-a-Punch! Upgrade your sniper or knife at the machine.",
        "Zombies: Kangabrew machine moved.",
        "Molotovs now have sounds.",
        "Zombies: molotovs! Zombies sometimes drop one. Throw it to set the ground on fire.",
        "The throwing knife key is now the Lethal key.",
        "Zombies: power-ups! Max Ammo, Insta-Kill, Double Points, Nuke and Bonus Points drop from zombies.",
        "Fixed jumping up through ceilings: you bump your head now.",
        "Fixed walking down ramps: smooth now, no repeated landing sound.",
        "New map: Ashes of the Damned.",
        "Zombies: buy sniper ammo at the ammo crate.",
        "Zombies: sniper ammo is now limited (40 rounds).",
        "Zombies: game over music.",
        "Zombies: new eerie ambience throughout the game.",
        "Picking up a throwing knife plays a sound.",
        "Zombies: you start with 2 throwing knives.",
        "A throwing knife that kills now drops beside the body.",
        "Thrown knives stay outlined in blue for a minute. Walk up and press F to pick one up.",
        "Menu button sounds are quieter.",
        "Main menu: background no longer flickers when clicking buttons.",
        "Zombies: machines buzz with electricity once the power's on.",
        "Zombies: perk machines stay dark and won't sell until the power's on.",
        "Zombies: a real power lever that everyone sees and hears thrown.",
        "New main menu background art, with drifting fog, embers and flicker.",
        "Main menu: Loadout and Settings no longer show the menu through them.",
        "Zombies: the ground breaks apart as zombies climb out.",
        "Zombies: a zombie goes quiet when killed, only its death cry plays.",
        "Fixed screen flickering after Shroom Tea wears off.",
        "Zombies: up to 150 zombies can be up at once.",
        "Zombies: new active enemies counter under enemies left.",
        "Zombies: zombies climb up ledges and rooftops after you.",
        "Zombies: no more getting stuck in walls.",
        "Zombies: zombies moan, groan as they rise, and cry out when they die.",
        "Zombies: hear zombie swipes landing, and the last zombie calling out.",
        "Zombies: speed climbs every round, up to a Nitro Brew sprint by round 50.",
        "Shroom Tea: zombies glow through walls again.",
        "Zombies: party leader can set the starting round and points.",
        "Zombies: perks and power now cost real prices (1,500–2,500; power 750).",
        "Zombies: no more piling into one spot; each shambles in its own way.",
        "Zombies: real zombies — they shamble, run and claw instead of shooting.",
        "Zombies: new Kangabrew perk — jump higher and off walls.",
        "Zombies: new Bomb Shot perk — 360 no-scope kills explode.",
        "New main menu music.",
        "Zombies: round number on screen, with a sound and animation each new round.",
        "Zombies: turn on the power on Break Point Night to light up the map.",
        "Zombies: real, solid perk machines for every perk.",
        "Liquid Courage: strong double vision right after drinking.",
        "Zombies: perk machines play their jingle when anyone buys one.",
        "New melee key (E): quick knife stab straight from the sniper.",
        "New Call of Duty style menus, lobby and loadout screens.",
        "New map: BREAK POINT NIGHT — full night, with gun flashlights.",
        "Red X on kills; hit markers now burst outward.",
        "Zombies: new, bigger perk icons.",
        "Shroom Tea: enemies only glow when hidden behind cover.",
        "Zombies: Shroom Tea and Liquid Courage hit hard for a few seconds after drinking.",
        "Zombies: new Liquid Courage perk — take less damage.",
        "Party leader can now pause the game from the Esc menu.",
        "Other players' rechamber is much quieter; no more aim sounds.",
        "Kill sound is a little quieter.",
        "Zombies: kill sound no longer plays twice.",
        "Zombies: new perk machine card with cost, points and ingredients.",
        "Zombies: perk icons line up in the order you bought them.",
        "Zombies: new Nitro Brew perk — move, aim, reload and swap faster.",
        "Zombies: you now drink Shroom Tea when you buy it.",
        "Zombies: buying Shroom Tea now plays a drink sound.",
        "Zombies: enemies-left counter on the left of the screen.",
        "Shroom Tea adds a slight aim assist while aiming down sight.",
        "Shroom Tea lets you see enemies through walls.",
        "Zombies: party points, health and names in the bottom left.",
        "Zombies: owned perks show as icons at the bottom.",
        "Zombies: buy the Shroom Tea perk on Break Point.",
        "New mode: ZOMBIES. Survive rounds of bots with your party.",
        "Throwing knives now leave a faint trail, in kill cams too.",
        "You can now jump just after running off a ledge.",
        "You can no longer run through other players and bots.",
        "Bots now have dark blue armour so you can tell them apart.",
        "Ping bots in Freestyle with middle mouse; your whole lobby sees it.",
        "Added name tags over players (blue in Freestyle, red in Free For All).",
        "Freestyle bots now use the soldier model and walk around the map.",
        "Added a ping (ms) readout beside the FPS counter.",
        "Sniper ammo is now limited in Free For All: 6 mags per life.",
        "New Call of Duty style ammo HUD, with throwing knives shown.",
        "Throwing knives are now limited: 2 per life in Free For All.",
        "Removed the Ascension map.",
        "Other players (and bots) now show a bright sniper glint off their scope while they're aiming down sight — just like Call of Duty, it can give away a camping sniper's position.",
        "Fixed the red tint and blood splatter overlay covering up your HUD (health, ammo, hit markers, etc) when you take damage or die. It now stays behind all on-screen text and UI.",
        "Fixed the red tint and blood splatter (and heartbeat) staying on screen after you respawn. Respawning now fully resets you: health, the hurt effects, camera shake, aiming, sprint / slide / mantle state, and any half-finished trick or shot. The server brings you back to life the moment you respawn, too, so skipping your kill cam no longer leaves you unable to hit anyone until a timer runs out.",
        "Fixed being able to move, aim, shoot and throw knives after being killed while waiting for the kill cam to start. Once you're dead you can't do anything except open the menu with Escape and use it.",
        "Kill cams now show everyone else as they really were during the replay: bots and other players walk, aim, crouch, jump and fall over when and where they actually did, instead of standing frozen where they were at the moment of the kill.",
        "The moment a Free For All match ends (kill limit reached or time up) the game freezes for 2 seconds: no movement, aiming or shooting, and nothing that happens counts. The screen flashes white, then VICTORY (green) or DEFEAT (red) slams in. After that the end-of-match replay plays — and it can no longer be skipped — then the final results screen.",
        "Free For All matches now end with a replay for everyone, whoever won. The party leader picks which in the lobby (everyone can see the choice): BEST PLAY — the most kills one player got within 8 seconds, replayed from a few seconds before the first kill to just after the last (two quick kills make a short replay; five kills in 8 seconds play the whole 8) — or FINAL KILL — just the last kill of the match. Both play with the same ramped slow-mo as Freestyle's best play.",
        "New map: BREAK POINT, a walled compound of low buildings, blocks and raised walkways, on a bright, cloudless mid-day with crystal-clear visibility all the way to the horizon. Pick it from the map buttons in the lobby.",
        "The Ascension map is now the same scale as the basic map (35% smaller all round), so it feels the right size to move around in. Bots on it also get around ledges and ramp turns better.",
        "Kill cams of a bot killing you look much more natural: the bot now scopes in gradually instead of snapping to full aim, and you see its rifle recoil, camera shake and bolt-cycle after each shot.",
        "Shipment (and Shipment Day) now has 11 fixed spawn points. When a match starts, and every time anyone respawns, players and bots appear at a random one of them, already facing the direction set for it and looking level.",
        "Bots now find their way around: they plan a route through the map (around walls and containers, up and down ramps) instead of walking straight at you.",
        "Free For All lobbies can now have bots! The party leader picks a number (up to 20) and a difficulty (Recruit, Regular, Hardened or Veteran) and presses ADD BOTS — add as many batches as you like, up to 20 bots in total. Bots show up in the party with their own names, walk around the map and shoot at everyone: you and each other. If one kills you, you get a kill cam of it. (They're basic for now: no pathfinding, so they can get stuck behind walls.)",
        "New map: ASCENSION, a multi-level blockout you climb by ramps, set on a snowy mountain hillside under a slightly overcast sky. Pick it from the map buttons in the lobby.",
        "Health is now handled entirely by the server: fall damage and shot damage take from the same health bar, and the red tint, blood splatter and heartbeat now also show when you're shot without being killed. Falls hurt in Freestyle too.",
        "Sniper damage now depends on distance too. Up close every hit kills, even a leg shot; further out a leg shot stops killing (past about 70 m), then a torso shot (past about 175 m), and at extreme range (past about 250 m) even a headshot leaves the target alive.",
        "Sniper shots are no longer always one-shot kills: a hit to the legs or lower body only does 60% damage, so the target survives (bots and players both have health now). When you damage but don't kill someone you get a hit marker and sound. In Free For All, damaged players heal back after 3 seconds.",
        "Fall damage: landing from a big drop now hurts in proportion to how far you fell (nothing under 16 m, dead at 30 m). When you're hurt the screen tints red with a blood splatter and you hear a heartbeat, both stronger the lower your health. Health holds for 3 seconds, then builds back up.",
        "The throwing arms (and the knife in their hand) now sway when you turn and breathe while you stand still, just like the sniper, and the regular knife now breathes too.",
        "Added a sound for switching to the sniper (only you hear it).",
        "Added knife sounds: an equip sound when you switch to the knife (only you hear it), a stab sound when you stab a bot or player (everyone hears it from the victim), and a swing sound when you attack and miss (everyone hears it from you). Volumes are in the debug panel. Throwing knife impact sounds are also quieter now.",
        "A thrown knife now makes an impact sound (one of several, picked at random) from the spot where it hits a wall, the ground or a crate. Everyone in the lobby hears it, and each clip has its own volume slider in the debug panel.",
        "Added throwing knife sounds: a throw sound when you let go (other players hear it from where you are), a whoosh that follows the knife through the air for everyone, and a hit sound from the spot where a thrown knife kills a bot or player. Volumes are in the debug panel.",
        "Shots now leave bullet holes on the surfaces they hit, and everyone in the lobby sees them. They disappear after a minute.",
        "Fixed: the throwing knife crosshair now shows in kill cams (and stays up while the throwing arms are on screen) instead of the plain centre dot.",
        "Fixed: kill cams now show the throwing arms and the knife being thrown (and flying, bouncing and landing the kill), instead of leaving them out.",
        "Shots no longer go through walls, crates or containers: a bullet (and its tracer) stops at the first surface it hits, so you can't hit anything behind cover.",
        "You can now actually throw the throwing knife! Hold V, aim and let go. It flies in an arc, bounces off walls and the ground, losing speed each time, then stops and disappears. Everyone in the lobby sees it. In Freestyle it kills bots (40 points); in Free For All it kills other players.",
        "The throwing arms now hold a throwing knife while you hold V. It disappears the moment the throw animation starts.",
        "Holding the throwing knife key (V) now quickly puts your weapon away, then slides a pair of throwing arms up from below. Let go and they play a throw animation and slide back down, and only then does your weapon come back. Press the swap-weapon key while holding to cancel without throwing. There is no knife to throw yet.",
        "Removed PRACTICE mode. Every game now runs through the server: create a lobby (or join one) and start it to play. Freestyle still gives you bots to shoot at.",
    ],
)];

/// The current version's notes — the main menu's "WHAT'S NEW" panel.
pub fn current() -> Option<(&'static str, &'static [&'static str])> {
    ENTRIES.first().copied()
}

/// Every older version's notes, newest first — the PAST UPDATES screen.
pub fn history() -> &'static [(&'static str, &'static [&'static str])] {
    ENTRIES.get(1..).unwrap_or(&[])
}
